### ISSUE TITLE
No USB Audio Galaxy S7 Edge + Fiio BTR5 Lineage OS 11

### ISSUE THREAD

**Issue by eudy97** [Magisk-Modules-Alt-Repo/usb-samplerate-unlocker#1]
When I enable this module on magisk, my BTR5 screen now says 384k instead of 96k, but no audio comes through the DAC and it comes through phone speakers intermittently for a few seconds at a time.

If I tried to run the USB_SampleRate_changer script without this modules, it errors out saying that it needs it.

Any suggestions?

**Comment by yzyhk904** [comment]
Please check whether you can hear sound with usb-samplerate-unlocker when USB_SampleRate_changer has not been used after reboot. I guess you can hear sound in this case. Perhaps, 386kHz 32bit mode.

I think there are some audio configuration mismatches when using USB_SampleRate_Changer.
Try `--safest` and `--usb-only` options separately  with a sample rate and 32 (bit depth) arguments.

Edit: I forgot to list the most likely cause. Your SELinux environment may possibly be somehow wrong. Try `setenforce 0` before using USB_SampleRate_Changer.

**Comment by eudy97** [comment]
> Please check whether you can hear sound with usb-samplerate-unlocker when USB_SampleRate_changer has not been used after reboot. I guess you can hear sound in this case. Perhaps, 386kHz 32bit mode.
> 
> I think there are some audio configuration mismatches when using USB_SampleRate_Changer.
> Try `--safest` and `--usb-only` options separately  with a sample rate and 32 (bit depth) arguments.
> 
> Edit: I forgot to list the most likely cause. Your SELinux environment may possibly be somehow wrong. Try `setenforce 0` before using USB_SampleRate_Changer.

No sound comes from the DAC with usb-samplerate-unlocker after enabling the module and rebooting. Sound only comes from the phone speakers.

The DAC screen does show 384k right off the bat after enabling the module and restarting but when I tried different sample rates using USB_SampleRate_Changer the DAC still shows 384k and sound will still come from the speakers.

Disabling the module and rebooting will give me 96k through the DAC but then I can't use USB_SampleRate_Changer.

Changed SELinux to permissive and tried --safest and --usb-only parameters separately and while they don't return any errors nothing happens on the DAC screen.

**Comment by yzyhk904** [comment]
Um, I guess the audioserver on your OS dislikes and rejects 386kHz audio devices. If you like, try replacing "full" with "default" in "/data/adb/modules/usb-samplerate-unlocker/post-fs-data.sh", and rebooting. This changes from "up to 386kHz" unlocking to "up to 192kHz" unlocking.

I think USB_SampleRate_changer (with --usb-only) can be used to the default 96kHz locked USB driver for changing from 96kHz 32bit mode to 44.1kHz or 48kHz 32bit mode.
