### ISSUE TITLE
No audio on Pixel 6

### ISSUE THREAD

**Issue by Epikest** [Magisk-Modules-Alt-Repo/usb-samplerate-unlocker#10]
after flashing the module, there is no sound playing from any sources.

**Comment by yzyhk904** [comment]
Do you mean your Pixel6 cannot replay tracks even through internal speakers?

If you Pixel6 cannot replay tracks only for USB devices, I guess your USB device needs a larger USB transfer period than that of this module. As far as I know, there is no such USB device. But there may be.

Try executing a command `extras/change-usb-period.sh --reset`. This command reverts the period (2250usec) to the stock value (5000usec).

**Comment by Epikest** [comment]
> Do you mean your Pixel6 cannot replay tracks even through internal speakers?

yes

**Comment by yzyhk904** [comment]
Do you use the spatial audio feature? USB_SampleRate_changer doesn't support the feature.

If this issue happens without executing USB_SampleRate_changer, let me know. I think the stock audio policy configuration is for the feature and you can replay tracks with the feature even after installing usb_samplerate_unlocker.

**Comment by Epikest** [comment]
yes, i use spatial audio. i'll try it out with it disabled. are there plans for supporting it?

**Comment by Epikest** [comment]
i turned it off and there is still no audio.

**Comment by yzyhk904** [comment]
My modules never support the spatial audio feature because its framework increases jitter significantly and degrades audio fidelity.

Can you output any sound through internal speakers without executing USB_SampleRate_Changer.sh after rebooting (with usb_samplerate_unlocker)? The spatial audio feature isn't related to usb_samplerate_unlocker.

If no sound though, I guess "/vendor/etc/audio_platform_configuration.xml" is broken somehow. Please copy the file after rebooting with the module, and attach copied one here.

**Comment by Epikest** [comment]
it's empty

**Comment by yzyhk904** [comment]
My module is running without issues on Pixel 6a here. And I've heard the same on also Pixel 8 Pro.

Someone said before one of my modules didn't work on another root tool (not Magisk). Don't you use another root tool or other magisk audio modules of other dev.?

**Comment by Epikest** [comment]
none, but i have a custom kernel (Kirisakura) and use Magisk Alpha.

**Comment by yzyhk904** [comment]
Magisk Alpha isn't Magisk, is it? Please check my module on pure Magisk.

Edit:
If you like, test my testing module ([magisk-module-usb-samplerate-unlocker-testing.zip](https://github.com/Magisk-Modules-Alt-Repo/usb-samplerate-unlocker/files/14391887/magisk-module-usb-samplerate-unlocker-testing.zip)). 
By any chance, it may work on other Magisk's.

**Comment by Epikest** [comment]
i don't think i can downgrade easily. i tested the module you provided and it didn't change anything still.

**Comment by yzyhk904** [comment]
I have a developing tool (root sh script) for changing "/vendor/etc/audio_platform_configuration.xml" on the fly. This tool may change the sample rate limit from 96kHz to 192kHz on your Pixel 6. Will you try this?

[Audio_Platform_Changer.zip](https://github.com/Magisk-Modules-Alt-Repo/usb-samplerate-unlocker/files/14395310/Audio_Platform_Changer.zip)

Unzip on /sdcard or else, then execute `/sdcard/Audio_Platfom_Changer/Audio_Platform_Changer.sh 192k`.

**Comment by Epikest** [comment]
it works when i disable spatial audio in conjunction with usb_samplerate_unlocker, however only up to 192k. 384k is silent.

**Comment by yzyhk904** [comment]
Pixel 6's, 7's and 8's have a limiter of sample rates at 192kHz in their kernel module, so you cannot set sample rate over 192kHz. Recent Pixel 7's and 8's set 192kHz for hires. tracks by default though.

If you want higher than 192kHz sample rates, a propriety usb driver (which cannot be used for usual streaming players) is needed like UAPP.

**Comment by Epikest** [comment]
ok thanks
