### ISSUE TITLE
For all of your audio modules, I cannot install them on KernelSU

### ISSUE THREAD

**Issue by kgursu** [Magisk-Modules-Alt-Repo/usb-samplerate-unlocker#12]
My goal is to update your audio modules, which I always install on all of my devices.
I cannot install them properly. I presumed an uninstall/reinstall will fix these, but I cannot add them to the installed modules list again.

Here are all KernelSU logs for those installs.
[KernelSU_install_log_2024-02-26-19-00-03.log](https://github.com/Magisk-Modules-Alt-Repo/usb-samplerate-unlocker/files/14411388/KernelSU_install_log_2024-02-26-19-00-03.log)
[KernelSU_install_log_2024-02-26-19-04-02.log](https://github.com/Magisk-Modules-Alt-Repo/usb-samplerate-unlocker/files/14411389/KernelSU_install_log_2024-02-26-19-04-02.log)
[KernelSU_install_log_2024-02-26-19-04-18.log](https://github.com/Magisk-Modules-Alt-Repo/usb-samplerate-unlocker/files/14411390/KernelSU_install_log_2024-02-26-19-04-18.log)
[KernelSU_install_log_2024-02-26-19-50-13.log](https://github.com/Magisk-Modules-Alt-Repo/usb-samplerate-unlocker/files/14411391/KernelSU_install_log_2024-02-26-19-50-13.log)

Here is a recent bootlog:
[bootlog-2024-02-26-20-46-12.tar.gz](https://github.com/Magisk-Modules-Alt-Repo/usb-samplerate-unlocker/files/14411426/bootlog-2024-02-26-20-46-12.tar.gz)

Here is KernelSU logs gathered from its directory:
[boot.log](https://github.com/Magisk-Modules-Alt-Repo/usb-samplerate-unlocker/files/14411434/boot.log)
[boot.old.log](https://github.com/Magisk-Modules-Alt-Repo/usb-samplerate-unlocker/files/14411436/boot.old.log)

I recently updated KernelSU to version 0.8.1. I wanted my kernel provider to update his kernel, he gave me a sample, but that also didn't help.
Could the recent KernelSU app be the cause?
Please give me instructions to solve this or direct me to the source of the problem.

Thanks.

**Comment by yzyhk904** [comment]
I assume my modules are handled by Magisk and they refer ROM's original files through Magisk's mirrored files, i.e., "$(magisk --path)/.magisk/mirror/vendor" for avoiding modified ones by themselves for properly updating already installed modules.

In short, my modules need "magisk" binary for getting the place where original files are, and magisk's magic mount system.

**Comment by yzyhk904** [comment]
I don't know kernelSU well, but I guess that moving file creation processes in "customize.sh" (only once) into "post-fs-data.sh" (at every boot time) makes compatible with kernelSU. This is Inefficient but may work.

**Comment by kgursu** [comment]
Ok, I'll be glad, if you could make it compatible. It was working before the recent KernelSU update.
I was a user of your three modules, Audio jitter silencer, USB Samplerate unlocker and Audio misc settings. After carefully searching through your repositories for the updates, I found out your Hifi maximizer module. It seems, it includes most of the options of these three modules, added some extensive features. It seems, if you have those there, you don't need that additionally, maybe instead of those three. Would you clarify this?
Also, I'm not a fan of permissive SELinux. If so, would HiFi maximizer module not suitable for me?
Thanks.

**Comment by yzyhk904** [comment]
Uum, I think you should request KenerlSU dev. to fix this issue, or use magisk instead of kernelSU.

See README of Hifi maximizer, in short "Hifi maximizer" includes "Audio Misc. Settings" + "DRC remover" + "extras/jitter-reducer.sh" (in "USB_SampleRate_Changer"). You'll need "Audio Jitter Silencer" additionally. If you want to use "USB_SampleRate_Changer", you need "USB Samplerate Unlocker" additionally too.

**Comment by kgursu** [comment]
That would be a broad request, I think. Which technical suggestion do you want me to pass on?

Thanks for the quick summary though...

**Comment by yzyhk904** [comment]
I need mirrored partitions as Magisk offers for properly updating my module (already installed) by using "customize.sh" because of avoiding files already modified by the module itself.

Any way, I recommend you using Magisk instead of kernelSU.

I forgot explaining why "Hifi maximizer" changes SELinux permissive. The reason is that SELinux generates significant jitter (fluctuating the actual data rate of a sound track replaying) and makes sound foggy.

**Comment by kgursu** [comment]
Ok, thanks for the clarification.

Here is the feature request page I created for KernelSU.
[https://github.com/tiann/KernelSU/issues/1406]()
If you need or want to jump in, you may any time.

**Comment by kgursu** [comment]
He/she needs more info, would you care to join?

**Comment by yzyhk904** [comment]
kernelSU denied to be magisk compatible, so I added checking incompatible magisk variants for showing installation fail apparently.

**Comment by yzyhk904** [comment]
I released [Compatible Magisk-mirroring](https://github.com/yzyhk904/compatible-magisk-mirroring). You could install my modules on KernelSU if you edit them to replace "(magisk --path)" with "(ksu-magisk --path)" in their module ZIP files after installing "Compatible Magisk-mirroring" and rebooting.

**Comment by kgursu** [comment]
Thanks for your additional efforts. It may shed light on new paths for possibilities...

**Comment by yzyhk904** [comment]
I'm lament KernelSU not supporting magisk-mirroring though it's able to add a tiny script.
