### ISSUE TITLE
Incompatible Magisk variant error

### ISSUE THREAD

**Issue by kgursu** [Magisk-Modules-Alt-Repo/usb-samplerate-unlocker#15]
I have been using Magisk Kitsune with all of your modules for a long time and there were literally no errors since then.
When and how would both become incompatible?
Solution please...

**Comment by yzyhk904** [comment]
I don't know the exact day, but maybe since mid February. It occurs apparently only when installing and updating the modules.

Try [Compatible Magisk-mirroring](https://github.com/yzyhk904/compatible-magisk-mirroring).

**Comment by kgursu** [comment]
I did. With Kitsune Magisk, it seems to be fine, but with KernelSU, I cannot install both of modules, which have new versions.

Here are the KernelSU logs:
  _  __                    _ ____  _   _ 
 | |/ /___ _ __ _ __   ___| / ___|| | | |
 | ' // _ \ '__| '_ \ / _ \ \___ \| | | |
 | . \  __/ |  | | | |  __/ |___) | |_| |
 |_|\_\___|_|  |_| |_|\___|_|____/ \___/ 

- Preparing image
- Module size: 71.95 kB
- Mounting image
- Device is system-as-root
Archive:  /data/user/0/me.weishu.kernelsu/cache/module.zip
  inflating: module.prop
**********************
 Audio misc. settings 
 by zyhk 
**********************
*********************
 Powered by KernelSU 
*********************
Archive:  /data/user/0/me.weishu.kernelsu/cache/module.zip
  inflating: customize.sh
- Extracting module files
Archive:  /data/user/0/me.weishu.kernelsu/cache/module.zip
  inflating: changelog.md
  inflating: customize-functions.sh
  inflating: customize.sh
  inflating: LICENSE
  inflating: module.prop
  inflating: post-fs-data.sh
  inflating: README.md
  inflating: service.sh
  inflating: system.prop
  inflating: system.prop-workaround
  inflating: uninstall.sh
sh: /data/adb/modules_update/audio-misc-settings/customize.sh: line 6: magisk: not found
  ***  Aborted by an incompatible Magisk variant detection. Try again with pure Magisk! ***
- Error: Failed to install module script
Error: Failed to install module script

  _  __                    _ ____  _   _ 
 | |/ /___ _ __ _ __   ___| / ___|| | | |
 | ' // _ \ '__| '_ \ / _ \ \___ \| | | |
 | . \  __/ |  | | | |  __/ |___) | |_| |
 |_|\_\___|_|  |_| |_|\___|_|____/ \___/ 

- Preparing image
- Module size: 53.74 kB
- Mounting image
- Device is system-as-root
Archive:  /data/user/0/me.weishu.kernelsu/cache/module.zip
  inflating: module.prop
*************************
 USB Samplerate Unlocker 
 by zyhk 
*************************
*********************
 Powered by KernelSU 
*********************
Archive:  /data/user/0/me.weishu.kernelsu/cache/module.zip
  inflating: customize.sh
- Extracting module files
Archive:  /data/user/0/me.weishu.kernelsu/cache/module.zip
  inflating: changelog.md
  inflating: customize.sh
  inflating: functions2.sh
  inflating: LICENSE
  inflating: module.prop
  inflating: post-fs-data.sh
  inflating: README.md
  inflating: system.prop
sh: /data/adb/modules_update/usb-samplerate-unlocker/customize.sh: line 6: magisk: not found
  ***  Aborted by an incompatible Magisk variant detection. Try again with pure Magisk! ***
- Error: Failed to install module script
Error: Failed to install module script

![Screenshot_20240328-170247_1.png](https://github.com/Magisk-Modules-Alt-Repo/usb-samplerate-unlocker/assets/35314872/8a5e58c3-58a8-44e7-8417-7b7de522728c)

**Comment by kgursu** [comment]
I saw the new version recently, but it didn't solve this issue. Shall I open a new issue here?
Bootlog: ![bootlog-2024-03-28-19-05-20.tar.gz](https://github.com/Magisk-Modules-Alt-Repo/usb-samplerate-unlocker/files/14792548/bootlog-2024-03-28-19-05-20.tar.gz)

**Comment by yzyhk904** [comment]
See README carefully!
