### ISSUE TITLE
No recovery after install

### ISSUE THREAD

**Issue by comradekingu** [Magisk-Modules-Alt-Repo/usb-samplerate-unlocker#2]
Upgraded to v1_4_0-1400 of this module and [Cross compiled modules for Android](https://github.com/Zackptg5/Cross-Compiled-Binaries-Android) (at the same time) from Fox mmm.
This left me with only the bootloader available after the reboot, since neither normal boot or recovery works.
That also means I can't get adb access to remove modules?

The camera stopped working beforehand (possibly also due to the protection for use that I forget the name of) so not ruling out general corruption.

Moto G7 Power (Ocean) XT1955-4

    LineageOS 17.1
        Magisk 24.1?
    Some other modules installed. Bootloop protection, some font thing, etc.

Can I reflash TWRP, or the rom without deleting user data to fix this?
Help much appreciated :)

Also posted this in https://github.com/Zackptg5/Cross-Compiled-Binaries-Android/issues/76

**Comment by yzyhk904** [comment]
I've never heard such things till now. "usb-samplerate-unlocker" is a simple module that overlays "/vendor/lib64/libalsautils.so" linked to "/vendor/lib64/hw/audio.usb.default.so" (an ALSA hardware driver module) with its modified one at each boot time. Even if the "libalsautils.so" was broken at boot, only the USB audio feature couldn't be used, I think.

"usb-samplerate-unlocker" uses "xxd", "sed", "tr" and "awk" at each boot time. Do you think something related to this issue?

If you can install TWRP and use a terminal emulator,  try "touch /data/adb/modules/usb-samplerate-unlocker/disable".

**Comment by comradekingu** [comment]
Didn't find anything untowards in the logs. Anything in particular that could indemnify this module?
Installed the newest TWRP available for the device (3.5.2_10.0) and wiping Dalvik booted up LineageOS again.
That also removes root.
Maybe some race-condition of installing the two at the same time?

**Comment by yzyhk904** [comment]
Do you mean "xxd" command is in the race condition?
I think "xxd" command is in Magisk's busybox.
