### ISSUE TITLE
Doesn't work on Pixel 8 Pro

### ISSUE THREAD

**Issue by The-Unforgiven-One** [Magisk-Modules-Alt-Repo/usb-samplerate-unlocker#6]
Installed this module on my Pixel 8 Pro however it is not working as my DAC say that it is still limited to 96khz however when I use the same DAC on a Pixel 6 Pro using your module and the same player and song it plays at 192khz.

**Comment by yzyhk904** [comment]
I don't have Pixel 8's, but their configuration XML file says they are originally 192kHz capable. You don't need the module on Pixel 8's (but still Pixel 6'a and 7's are 96kHz limited and need the module).

I guess you replayed non-hires. tracks on Pixel 8 Pro or hires. tracks with spatial effect, i.e., you replayed them at 48kHz (not 96kHz) with the DAC. If so, try hires. tracks without spatial effect.
